{{- if .Values.createIngress }}
{{- if semverCompare ">=1.19.0-0" .Capabilities.KubeVersion.GitVersion -}}
apiVersion: networking.k8s.io/v1
{{- else -}}
apiVersion: networking.k8s.io/v1beta1
{{- end }}
kind: Ingress
metadata:
{{- if or .Values.ingressAnnotations .Values.gke.useGKEIngress }}
  annotations:
{{- range $key, $value := $.Values.ingressAnnotations }}
    {{ $key }}: {{ $value | quote }}
{{- end }}
  {{- if .Values.gke.ingress.useGKEIngress }}
    kubernetes.io/ingress.class: gce
    {{- if .Values.gke.ingress.useManagedCertificate }}
    kubernetes.io/ingress.allow-http: "false"
    networking.gke.io/managed-certificates: fleet
    {{- end }}
  {{- end }}
{{- end }}
  labels:
    app: fleet
    chart: fleet
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
  name: fleet
  namespace: {{ .Release.Namespace }}
spec:
  rules:
  - host: {{ .Values.hostName }}
    http:
      paths:
      - path: /*
      # Next block required in k8s =>1.19 and not supported in <=1.17
      {{- if semverCompare ">=1.19.0-0" .Capabilities.KubeVersion.GitVersion }}
        pathType: Exact
        backend:
          service:
            name: fleet
            port:
              number: fleet
        {{- else }}
        backend:
          serviceName: fleet
          servicePort: fleet
        {{- end }}
{{- end }}
